<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1527393364660" stop="1527393364907">
  <name>test_03lx02</name>
  <labels/>
  <test-cases>
    <test-case start="1527393364660" status="failed" stop="1527393364907">
      <name>Test_01.test_001</name>
      <failure>
        <message>AssertionError: assert 1 == 2</message>
        <stack-trace>self = &lt;test_03lx02.Test_01 object at 0x0000000003D90DA0&gt;, fix = [1, 2]

    def test_001(self,fix):
        for i in fix:
&gt;           assert i == 2
E           assert 1 == 2

scripts\test_03lx02.py:10: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="1568-MainThread"/>
        <label name="host" value="PC201509071647"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
